# Site settings
title: Hongyuan Yu
SEOTitle: 俞宏远的博客 | Hongyuan Blog
header-img: img/homepage_4.jpg
email: yuhyuan1995@gmail.com
# description: "When natural inclination develops into a passionate desire, one advances towards his goal in seven-league boots."
keyword: "Hongyuan, Blog, ML, CV"
url: "http://hongyuan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hongyuanyu/hongyuanyu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "PHD of Institute of Automation, Chinese Academy of Sciences"
sidebar-avatar: /img/hongyuan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    hongyuanyu
#facebook_username:  baiying.qiu.7
jianshu_username:   Arti_Silly
twitter_username:   GoGo61716923




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: hongyuanyu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 10e3ca80a8ef3935d3b9                            #生成的clientID
  clientSecret: 3f169df87c2ade38c28cabe038cba8cb7eeb9b72    #生成的clientSecret
  repo: hongyuanyu.github.io    #仓库名称
  owner: hongyuanyu    #github用户名
  admin: hongyuanyu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68
ba_track_id: f1ba05de6bfde557aba4900a681b0cb1

# Google Analytics
ga_track_id: 'UA-130299619-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Hongyuan Yu",
        href: "CASIA"
    },{
        title: "简书·Arti_Silly",
        href: "https://www.jianshu.com/u/0f0fd65df64a"
    }
]
